### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by WhiteRedWolf** [WhiteRedWolf/Polygon#1]
- [ ] Fix Issue for GameWindow Stopping Int
- [ ] Add Main Menu
- [ ] Add Gameset "poly.Gamesets.Polygon"
- [ ] Add Options Menu
- [ ] Add Exit Menu
- [ ] Add Online Captabilities
- [ ] Add IRC Chat
- [ ] Add Online Leaderboards "Score Leaderboards"
- [ ] Add Overall Score Leaderboards
